version: '3'
services:
  website-v2:
    build: .
    volumes:
      - ./config/env.json:/app/config/env.json
      - ./ecosystem.config.js:/app/ecosystem.config.js
      - ./config/keys:/app/config/keys
    ports:
      - 80:80
